version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose app's port 8080 to host's port 8080
    depends_on:
      - redis
    environment:
      REDIS_ADDR: "redis:6379" # Use service name for Redis
      GIN_MODE: release # Optional: set Gin to release mode

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Expose Redis's port 6379 to host's port 6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: # Persist Redis data
